---
- name: AroCD App
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.app_namespace | default('argocd') }}"
      spec:
        destination:
          namespace: "{{ item.destination_namespace }}"
          server: https://kubernetes.default.svc
        project: default
        source:
          directory:
            jsonnet: {}
            recurse: true
          path: "{{ item.repo_path }}"
          repoURL: "{{ item.repo_url }}"
          targetRevision: "{{ item.repo_target_revision | default('main') }}"
        syncPolicy:
          automated:
            prune: "{{ item.auto_prune | default(False) }}"
            selfHeal: "{{ item.self_heal | default(False) }}"
          syncOptions: "{{ item.sync_options | default([]) }}"
      status: {}

