---
- name: RKE2 Server | Place configation
  ansible.builtin.template:
    src: server-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0660"
  become: yes

- name: RKE2 Server | Enable and start Systemd service
  ansible.builtin.systemd_service:
    name: rke2-server.service
    state: started
    enabled: yes
  poll: 5
  async: 600
