---
- name: RKE2 Server | Place configation
  ansible.builtin.template:
    src: server-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0660"
  become: yes
  notify: Restart rke2-server

- name: RKE2 Server | Enable and start Systemd service
  ansible.builtin.systemd_service:
    name: rke2-server.service
    state: started
    enabled: yes
  poll: 5
  async: 600
  become: yes
  register: rke2_server_status

- name: RKE2 Server | Wait until service is active
  ansible.builtin.systemd_service:
    name: rke2-server.service
    state: started
  retries: 30
  delay: 10
  register: result
  until: result.status.ActiveState == "active"
  become: yes
