---
- name: Kubectl | Fetch binary
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/{{ rke2_version.split('+')[0] }}/bin/linux/{{ rke2_arch }}/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    owner: root
    group: root
    follow_redirects: all
  become: yes

- name: Kubectl | Create .kube directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Kubectl | Make sure root can find kubectl
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: '[[ "$PATH" =~ "/usr/local/bin" ]] || export PATH="/usr/local/bin:$PATH" # Added by rke2 playbook'
  become: yes
