---
- name: Get latest Kube-VIP version
  delegate_to: localhost
  become: no
  run_once: true
  ansible.builtin.uri:
    url: https://api.github.com/repos/kube-vip/kube-vip/releases
    return_content: true
  register: kubevip_version_raw

- name: Generate Kube-VIP static pod manifest
  become: no
  delegate_to: localhost
  run_once: true
  vars:
    kubevip_address: 192.168.122.30
    kubevip_version: "{{ kubevip_version_raw.json[0]['name'] }}"
    kubevip_interface: "{{ ansible_default_ipv4.interface }}"
    kubeconfig_path: /root/.kube/config
  ansible.builtin.command: >-
    podman
    run
    --rm
    ghcr.io/kube-vip/kube-vip:{{ kubevip_version }}
    manifest
    pod
    --interface {{ kubevip_interface }}
    --address {{ kubevip_api_address }}
    --controlplane
    --arp
    --leaderElection
  changed_when: false
  register: kubevip_manifest
  become: no

- name: Create static manifests directory
  become: yes
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/pod-manifests
    state: directory

- name: Write Kube-VIP manifest
  become: yes
  ansible.builtin.copy: 
    dest: /var/lib/rancher/rke2/agent/pod-manifests/kubevip.yaml
    content: "{{ kubevip_manifest.stdout | regex_replace('path: \\/etc\\/kubernetes\\/admin\\.conf', 'path: /root/.kube/config.yaml') }}"
    owner: root
    group: root
