---
- name: Pre-installation tasks
  ansible.builtin.include_tasks: pre-install.yaml

- name: Common installation steps
  ansible.builtin.include_tasks: install_common.yaml

- name: RKE2 Server
  ansible.builtin.include_tasks: install_server.yaml
  when:
    - '"rke2_server" in group_names'

- name: RKE2 Agent
  ansible.builtin.include_tasks: install_agent.yaml
  when:
    - '"rke2_agent" in group_names'

- name: Kubectl
  ansible.builtin.include_tasks: kubectl.yaml

- name: Helm
  ansible.builtin.include_tasks: helm.yaml

- name: CSI-driver-SMB
  ansible.builtin.include_tasks: csi-driver-smb.yaml

- name: Volumes
  ansible.builtin.include_tasks:
    file: volumes.yaml
    apply:
      tags:
        - volumes
  loop: "{{ rke2_hostpath_volumes }}"
  tags:
    - volumes
