---
- name: Post-install | Label nodes
  delegate_to: "{{ groups['rke2_server'][0] }}"
  kubernetes.core.k8s:
    state: patched
    api_version: v1
    kind: Node
    name: "{{ inventory_hostname | lower }}"
    definition:
      metadata:
        labels: "{{ rke2_additional_node_labels }}"
  become: yes

- name: Post-install | Provision additional secrets
  delegate_to: "{{ groups['rke2_server'][0] }}"
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Secret
    namespace: "{{ item.namespace }}"
    name: "{{ item.name }}"
    definition:
      data: "{{ item.data | default(omit) }}"
      stringData: "{{ item.stringData | default(omit) }}"
  loop: "{{ rke2_additional_secrets }}"
  become: yes
