---
- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
  become: yes

- name: Reload NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: reloaded
  become: yes

- name: Reboot if old NetworkManager
  ansible.builtin.reboot:
  when:
    - "'NetworkManager' in ansible_facts.packages"
    - ansible_facts['packages']['NetworkManager']['version'] is version('1.30.0', '<')
  become: yes
