---
- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: yes
  become: yes

- name: Reload NetworkManager
  ansible.builtin.systemd_service:
    name: NetworkManager
    state: reloaded
  become: yes

- name: Reboot if old NetworkManager
  ansible.builtin.reboot:
  when:
    - "'NetworkManager' in ansible_facts.packages"
    - ansible_facts['packages']['NetworkManager'][0]['version'] is version('1.30.0', '<')
  become: yes

- name: Restart rke2-server
  ansible.builtin.systemd_service:
    name: rke2-server
    state: restarted
  become: yes
  when: not rke2_server_status.changed

- name: Restart rke2-agent
  ansible.builtin.systemd_service:
    name: rke2-agent
    state: restarted
  become: yes
  when: not rke2_agent_status.changed

- name: Reload sysctl
  ansible.builtin.command: /usr/sbin/sysctl -p
  become: yes
